window.MATH_DESK_DATA = {
  book: "四年级上册 · 人教版（2024 审定）",
  brand: "数学书桌",
  currentUnitId: "u02",
  currentTrack: "daily",
  /**
   * 对齐人教版四上 2024 审定本目录（7 个正单元 + 活动课并入相邻单元日常）。
   * 考前卷：U1–U5 沿用已重排 A4 清晰卷（知识点大体可沿用，卷面标题已改）；
   * U6–U7 尚无按新教材对齐的原卷 → examComplete=false（待补）。
   */
  units: [
    {
      id: "u01",
      no: 1,
      name: "第一单元 · 万以上数的认识",
      short: "万以上数的认识",
      examPdf: "printables/u01/04-考前测试/U1_四上_第一单元_万以上数的认识_试卷.pdf",
      examAnswerPdf: "printables/u01/04-考前测试/U1_四上_第一单元_万以上数的认识_答案.pdf",
      examComplete: true,
      examPages: 4,
      wrongPdf: "printables/u01/05-错题库/u01-错题重练-模板.pdf",
    },
    {
      id: "u02",
      no: 2,
      name: "第二单元 · 角的度量",
      short: "角的度量",
      examPdf: "printables/u02/04-考前测试/U2_四上_第二单元_角的度量_试卷.pdf",
      examAnswerPdf: "printables/u02/04-考前测试/U2_四上_第二单元_角的度量_答案.pdf",
      examComplete: true,
      examPages: 4,
      wrongPdf: "printables/u02/05-错题库/u02-错题重练-模板.pdf",
    },
    {
      id: "u03",
      no: 3,
      name: "第三单元 · 多位数乘两位数",
      short: "多位数乘两位数",
      examPdf: "printables/u03/04-考前测试/U3_四上_第三单元_多位数乘两位数_试卷.pdf",
      examAnswerPdf: "printables/u03/04-考前测试/U3_四上_第三单元_多位数乘两位数_答案.pdf",
      examComplete: true,
      examPages: 2,
      wrongPdf: "printables/u03/05-错题库/u03-错题重练-模板.pdf",
    },
    {
      id: "u04",
      no: 4,
      name: "第四单元 · 加法模型和乘法模型",
      short: "加法模型和乘法模型",
      examPdf: "printables/u04/04-考前测试/U4_四上_第四单元_加法模型和乘法模型_试卷.pdf",
      examAnswerPdf: "printables/u04/04-考前测试/U4_四上_第四单元_加法模型和乘法模型_答案.pdf",
      examComplete: true,
      examPages: 2,
      wrongPdf: "printables/u04/05-错题库/u04-错题重练-模板.pdf",
    },
    {
      id: "u05",
      no: 5,
      name: "第五单元 · 平行四边形和梯形",
      short: "平行四边形和梯形",
      examPdf: "printables/u05/04-考前测试/U5_四上_第五单元_平行四边形和梯形_试卷.pdf",
      examAnswerPdf: "printables/u05/04-考前测试/U5_四上_第五单元_平行四边形和梯形_答案.pdf",
      examComplete: true,
      examPages: 2,
      wrongPdf: "printables/u05/05-错题库/u05-错题重练-模板.pdf",
    },
    {
      id: "u06",
      no: 6,
      name: "第六单元 · 条形统计图",
      short: "条形统计图",
      examPdf: "printables/u06/04-考前测试/U6_四上_第六单元_条形统计图_试卷.pdf",
      examAnswerPdf: "printables/u06/04-考前测试/U6_四上_第六单元_条形统计图_答案.pdf",
      examComplete: false,
      examPages: 0,
      wrongPdf: "printables/u06/05-错题库/u06-错题重练-模板.pdf",
    },
    {
      id: "u07",
      no: 7,
      name: "第七单元 · 复习与关联",
      short: "复习与关联",
      examPdf: "printables/u07/04-考前测试/U7_四上_第七单元_复习与关联_试卷.pdf",
      examAnswerPdf: "printables/u07/04-考前测试/U7_四上_第七单元_复习与关联_答案.pdf",
      examComplete: false,
      examPages: 0,
      wrongPdf: "printables/u07/05-错题库/u07-错题重练-模板.pdf",
    },
  ],
};
